/**
* @author Malgorzata Krawczyk <malgorzata.krawczyk@accenture.com>
* @date 30/08/2021
* @description This class contains constant values
**/
public class Constants {
/**
CONSTANTS FOR ACCOUNT OBJECTS
**/
    public static final String ACCOUNT_TEST_NAME = 'Test Account';

/**
CONSTANTS FOR CASE OBJECTS
**/
    public static final String SUBJECT_CASE_RENOVATION = 'Renovation Case';
    public static final String CASE_STATUS_NEW = 'New';
    public static final String CASE_STATUS_CLOSED = 'Closed';
    public static final String CASE_STATUS_FAILED = 'Failed';
    public static final String CASE_ORIGIN_PHONE = 'Phone';

/**
CONSTANTS FOR ALL OBJECTS
**/
public static final String ERROR_CONNECTING_MESSAGE = 'Error connecting';
public static final String ERROR_ENTRY_PARAMETR_NULL = 'Entry parametr is null!';
public static final String SENDER_DISPLAY = 'Email';

/**
CONSTANTS FOR REVIEW CAR DELETION OBJECTS
**/
public static final String REVIEW_NAME = 'Report ';
public static final String REVIEW_PREFIX = 'Deletion car with name ';

/**
CONSTANTS FOR CAR POSTING OBJECTS
**/
public static final String CAR_POSTING_TYPE_PHYSICAL = 'Physical';
public static final String CAR_POSTING_TYPE_VIRTUAL = 'Virtual';
public static final String ERROR_EXIST_PHYSICAL_OFFER = 'Only one physical offer could exist for this car!';
public static final String ERROR_AVAILABLE_CAR_QUANTITY = 'Available only car quantity: ';
public static final String SUBJECT_CAR_POSTING_EMAIL = 'Information about new car postings';
public static final String INFO_CAR_POSTING_EMAIL = ' New carPosting with name was added: ';

/**
CONSTANTS FOR CAR DEALERSHIP OBJECTS
**/
public static final String CAR_DEALERSHIP_STATUS_OPEN = 'Open';
public static final String CAR_DEALERSHIP_STATUS_CLOSE = 'Close';
public static final String ERROR_CAR_DEALERSHIP_CAR_QUANTITY = 'Car Quantity must be above 0!';

/**
CONSTANTS FOR ROLE AND USER OBJECTS
**/
public static final String ROLE_NAME = 'Director, Direct Sales';

/**
CONSTANTS FOR TELEMETRY OBJECTS
**/
public static final String TELEMETRY_TEST_NAME = 'Test Telemetry';
}
